version: "3.5"
services:

  app:
    build:
      target: dev
    command: yarn start:dev
    container_name: odonnellwedding
    image: nicholasodonnell/odonnellwedding:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - node-modules:/app/node_modules

volumes:
  node-modules:
