version: "3.5"
services:

  app:
    build:
      context: .
    expose:
      - 3000
    image: nicholasodonnell/odonnellwedding:latest
    networks:
      - odonnellwedding

networks:
  odonnellwedding:
    driver: bridge
    name: odonnellwedding
